version: '3.8'

services:
  app:
    image: finance-prod-app
    container_name: finance-prod-app
    build:
      target: prod
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    container_name: finance-prod-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: finance
    volumes:
      - finance_db_prod:/var/lib/postgresql/data

volumes:
  finance_db_prod:
