name: finance-prod

services:
  app:
    image: herytz/finance
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.production.local
    depends_on:
      - db
    pull_policy: always

  db:
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: finance
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
