name: finance-prod

services:
  app:
    image: finance-prod-app
    build:
      target: prod
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: finance
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    external: true
