on:
  push:
    branches:
      - main
  
jobs:
  production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - uses: ./.github/actions/docker-compose
      - name: Run tests
        run: |
          docker compose up -d
          pnpm test
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -p${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Update app
        run: |
          ssh -p${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ~/finance/app && \
            git pull origin main && \
            docker compose -f docker-compose.prod.yml up --build -d && \
            docker image prune -f"
